/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { ViewStrings } from '@skywalking-horizon-ui/conversation-view';

type Translate = (key: string, named?: Record<string, unknown>) => string;

/** The renderer's texts in the UI's locale. Every value is a literal `t()`
 *  call so the catalog check sees each key. A text with a placeholder is
 *  translated with the placeholder as its own value, so `{n}` survives for
 *  the renderer to fill in. */
export function conversationStrings(t: Translate): ViewStrings {
  return {
    round: t('round'),
    segments: t('segments'),
    streams: t('streams'),
    talks: t('talks'),
    span: t('span'),
    unresolved: t('unresolved'),
    overview: t('Overview'),
    session: t('Session'),
    steps: t('Steps'),
    runs: t('runs'),
    childStreams: t('Child streams'),
    childStreamsNote: t('subagents, each its own context'),
    relations: t('Relations'),
    activityWindows: t('activity windows'),
    idle: t('idle'),
    integrityVerified: t('verified'),
    integrityIncomplete: t('incomplete'),
    integrityMismatch: t('mismatch'),
    problems: t('problems'),
    roundsVerified: t('rounds verified'),
    filesListed: t('files'),
    filterTalks: t('filter'),
    noTalkMatches: t('No talk matches.'),
    untitled: t('(untitled)'),
    talk: t('Talk'),
    mainStreamCaption: t('main stream, child work folded'),
    childStreamCaption: t('child stream'),
    tools: t('tools'),
    externalInput: t('External · Input'),
    noOpeningLine: t('no opening line'),
    delegatedWork: t('delegated work'),
    showWork: t('show what the agent did'),
    hideWork: t('hide what the agent did'),
    quiet: t('quiet'),
    mainAgent: t('Main agent'),
    childAgent: t('Child agent'),
    agent: t('Agent'),
    response: t('Response'),
    streamOutput: t('Stream output'),
    clientMadeMessage: t('Client-made message · not from the provider'),
    contextPutIn: t('Context put in'),
    agentCallToChild: t('Agent call'),
    notificationFromChild: t('Runtime notification'),
    launchAcknowledged: t('Launch acknowledged'),
    modelCall: t('Model call'),
    reasoning: t('Reasoning'),
    toolWord: t('Tool'),
    callWord: t('call'),
    turn: t('turn'),
    input: t('input'),
    result: t('result'),
    failed: t('failed'),
    toReturn: t('to return'),
    openStream: t('Open'),
    independentStream: t('Independent stream context. Its messages are not merged into the parent.'),
    openedFrom: t('Opened from'),
    noOpenerRecorded: t('No relation records what opened it.'),
    backToOpener: t('← Back to the step that opened this'),
    noTalksInStream: t('No talks in this stream.'),
    outsideAnyTalk: t('Outside any talk'),
    outsideAnyTalkNote: t('Steps the fold could not place under a talk — a child’s output whose stream opened no talk, for instance. The document holds them so nothing is lost.'),
    childStreamsPick: t('child streams…'),
    childStreamSingular: t('child stream'),
    childStreamPlural: t('child streams'),
    backToStream: t('Back to'),
    showThisTalk: t('Show this talk in the flow timeline'),
    showThisAnswer: t('Show this talk’s answer in the flow timeline'),
    locateInTimeline: t('Locate in the flow timeline'),
    flowTimeline: t('Flow timeline'),
    timelineHelp: t('What is the flow timeline?'),
    parentTimeline: t('← Parent timeline'),
    fadeUnrelated: t('Fade unrelated'),
    fadeUnrelatedTitle: t('Fade the steps that the selected one does not touch'),
    zoom: t('Zoom'),
    centerSelected: t('Center selected'),
    centerSelectedTitle: t('Scroll the timeline to the selected step'),
    events: t('events'),
    nested: t('nested'),
    laneInput: t('External input'),
    laneResponses: t('Responses'),
    laneContext: t('Context put in'),
    laneModel: t('Model calls'),
    laneTools: t('Tools'),
    laneAgents: t('Agent activity'),
    laneNotices: t('Runtime notices'),
    laneNested: t('Nested streams'),
    legendInput: t('External input'),
    legendResponse: t('Agent response'),
    legendModel: t('Model call'),
    legendTool: t('Tool'),
    legendAgent: t('Agent / nested stream'),
    legendContext: t('Context / annotation'),
    legendOwns: t('Emitted by (ownership)'),
    legendExact: t('Exact join'),
    legendInferred: t('Strong inference'),
    agentsCreated: t('agents created'),
    poolTitle: t('This call started {n} child agents at nearly the same moment. Click, then pick one in the inspector.', { n: '{n}' }),
    reportedHere: t('It reported finishing in this talk.'),
    clickToSeeOpener: t('Click to see what opened it.'),
    helpWhat: t('what it shows'),
    helpWhatText: t('One talk, on a time axis. Each row is a lane: the messages, the model calls, the tools it ran, its agent activity, and the nested streams it started. The line above the lanes is the whole conversation, one cell per segment.'),
    helpHeading: t('the heading'),
    helpHeadingText: t('Which stream the lanes belong to, how many steps are in this talk, and how many nested streams it touches.'),
    helpAxis: t('the axis'),
    helpAxisText: t('Busy stretches take the width. A long pause is cut to a short gap marked with how long it was, so a talk with an hour of waiting still reads.'),
    helpLinks: t('links'),
    helpLinksText: t('The lines between lanes, drawn for the step you select. A solid line is an exact join, a dashed one was inferred, and a faint curve is ownership: the model call that produced a step.'),
    helpFade: t('fade unrelated'),
    helpFadeText: t('After you click a step, fade everything it does not touch.'),
    inspector: t('Inspector'),
    details: t('Details'),
    evidence: t('Evidence'),
    selectAStep: t('Select a step.'),
    nestedStream: t('nested stream'),
    stream: t('Stream'),
    role: t('Role'),
    openedBy: t('Opened by'),
    reportedHereBy: t('Reported here by'),
    note: t('Note'),
    reportedNote: t('this talk hears the ending. The call that started it is in an earlier talk, because a launch and its completion land in different turns.'),
    joinQuality: t('Join quality'),
    openedAt: t('Opened at'),
    itsAnswer: t('Its answer'),
    itsAnswerNote: t('not in this stream. A child’s output belongs to the child, so the parent holds a boundary that refers to it, never a copy. Dive in to read it.'),
    opensInTurn: t('Opens in turn'),
    opensNothing: t('nothing — it opened no stream of its own'),
    andMore: t('and {n} more', { n: '{n}' }),
    poolWarning: t('this call started {n} streams', { n: '{n}' }),
    poolWarningText: t('A workflow call starts a run, and the run starts a pool of agents. They are all its children, not competing guesses at one child.'),
    diveIn: t('Dive in →'),
    diveHint: t('Enter to dive in · Escape to clear'),
    nodeKind: t('Node kind'),
    lane: t('Lane'),
    segment: t('Segment'),
    run: t('Run'),
    directParent: t('Direct parent'),
    observedAt: t('Observed at'),
    requestToResult: t('Request to result'),
    duration: t('Duration'),
    durationUnavailable: t('unavailable — the runtime does not report how long this ran'),
    requestToResultWhat: t('What "request to result" is'),
    requestToResultText: t('The time between the record carrying the request and the record carrying the result. An exact identifier ties those two records together, so the interval belongs to this call. It is not how long the tool ran, and the runtime does not report that.'),
    name: t('Name'),
    failedField: t('Failed'),
    yes: t('yes'),
    no: t('no'),
    contentState: t('Content state'),
    contentBytes: t('Content bytes'),
    tokens: t('Tokens'),
    tokensText: t('in {in} · out {out} · cache read {cacheRead} · cache write {cacheWrite}', { in: '{in}', out: '{out}', cacheRead: '{cacheRead}', cacheWrite: '{cacheWrite}' }),
    contentUnavailable: t('Content {state}', { state: '{state}' }),
    contentUnavailableText: t('The source did not supply readable content for this step. It is reported as it was found, not filled in.'),
    oneChildAgent: t('1 child agent'),
    childAgents: t('{n} child agents', { n: '{n}' }),
    openRelations: t('open the Relations tab →'),
    backToParentStream: t('← Back to parent stream'),
    noRelation: t('No relation touches this step.'),
    agentsCreatedByCall: t('{n} agents created by this call', { n: '{n}' }),
    agentsCreatedText: t('A workflow call starts a run, and the run starts a pool of agents. Every one of them is a child of this call, not a competing guess at one child. Pick the one to read.'),
    outgoing: t('outgoing'),
    incoming: t('incoming'),
    joinedOn: t('joined on'),
    namedFromJournal: t('named from its run journal'),
    otherEndOutside: t('the other end is outside this stream'),
    derivedByAssembly: t('This step was derived by assembly. It cites no landed record.'),
    landedPositions: t('landed positions'),
    request: t('request'),
    part: t('part'),
    record: t('record'),
    clippedText: t('the text as the document carries it'),
    fullTextNote: t('clipped: {shown} of {total} bytes', { shown: '{shown}', total: '{total}' }),
    loadFullRecord: t('Load the landed record'),
    loadingRecord: t('reading…'),
    recordFailed: t('The record could not be read.'),
    theLandedRecord: t('the landed record'),
    dropped: t('dropped'),
    flags: t('flags'),
    unavailable: t('unavailable'),
    vocabulary: t('vocabulary'),
    modelOwnWord: t('the model’s own word'),
    aszTerm: t('asz term'),
    runtimeWord: t('runtime word'),
    runtimeNoWord: t('none — this is derived here, the runtime has no word for it'),
    whereToLook: t('where to look'),
    nowhereInSource: t('nowhere in the source; it is produced by assembly'),
    readCarefully: t('read it carefully'),
    dialect: t('dialect'),
    landedRecordField: t('a field of the landed record'),
    aszField: t('asz field'),
    whatItIs: t('what it is'),
    notApplicable: t('not applicable — this describes the landed record, not the source'),
    close: t('Close'),
    whatDoesMean: t('What does {key} mean?', { key: '{key}' }),
    selected: t('Selected {what}', { what: '{what}' }),
    selectedNestedStream: t('Selected nested stream {name}, opened by {kind}. Press Enter to dive in, Escape to clear.', { name: '{name}', kind: '{kind}' }),
    selectionCleared: t('Selection cleared.'),
  };
}
