/* eslint-disable */
/**
 * GENERATED by `pnpm proto:sync` from the vendored .proto in ./proto — DO NOT EDIT.
 * `pnpm proto:check` regenerates this file and fails on any diff.
 *
 * Types only. These describe what @grpc/proto-loader returns under the options
 * in ./proto.ts (keepCase, longs: String, enums: String, oneofs: true) — see
 * scripts/gen-proto-types.mjs.
 */

export namespace banyandb {
  export namespace common {
    export namespace v1 {
      export type Catalog = 'CATALOG_UNSPECIFIED' | 'CATALOG_STREAM' | 'CATALOG_MEASURE' | 'CATALOG_PROPERTY' | 'CATALOG_TRACE';
      export interface Metadata {
        group?: string;
        name?: string;
        id?: number;
        create_revision?: string;
        mod_revision?: string;
      }
      export interface IntervalRule {
        unit?: banyandb.common.v1.IntervalRule.Unit;
        num?: number;
      }
      export namespace IntervalRule {
        export type Unit = 'UNIT_UNSPECIFIED' | 'UNIT_HOUR' | 'UNIT_DAY';
      }
      export interface LifecycleStage {
        name?: string;
        shard_num?: number;
        segment_interval?: banyandb.common.v1.IntervalRule;
        ttl?: banyandb.common.v1.IntervalRule;
        node_selector?: string;
        close?: boolean;
        replicas?: number;
      }
      export interface ResourceOpts {
        shard_num?: number;
        segment_interval?: banyandb.common.v1.IntervalRule;
        ttl?: banyandb.common.v1.IntervalRule;
        stages?: banyandb.common.v1.LifecycleStage[];
        default_stages?: string[];
        replicas?: number;
      }
      export interface Group {
        metadata?: banyandb.common.v1.Metadata;
        catalog?: banyandb.common.v1.Catalog;
        resource_opts?: banyandb.common.v1.ResourceOpts;
        updated_at?: google.protobuf.Timestamp;
      }
      export interface APIVersion {
        version?: string;
        revision?: string;
      }
      export interface GetAPIVersionRequest {
      }
      export interface GetAPIVersionResponse {
        version?: banyandb.common.v1.APIVersion;
      }
      export interface Trace {
        trace_id?: string;
        spans?: banyandb.common.v1.Span[];
        error?: boolean;
      }
      export interface Span {
        start_time?: google.protobuf.Timestamp;
        end_time?: google.protobuf.Timestamp;
        error?: boolean;
        tags?: banyandb.common.v1.Tag[];
        message?: string;
        children?: banyandb.common.v1.Span[];
        duration?: string;
      }
      export interface Tag {
        key?: string;
        value?: string;
      }
    }
  }
  export namespace model {
    export namespace v1 {
      export interface Str {
        value?: string;
      }
      export interface Int {
        value?: string;
      }
      export interface Float {
        value?: number;
      }
      export interface StrArray {
        value?: string[];
      }
      export interface IntArray {
        value?: string[];
      }
      export interface TagValue {
        null?: google.protobuf.NullValue;
        str?: banyandb.model.v1.Str;
        str_array?: banyandb.model.v1.StrArray;
        int?: banyandb.model.v1.Int;
        int_array?: banyandb.model.v1.IntArray;
        binary_data?: Buffer;
        timestamp?: google.protobuf.Timestamp;
        value?: 'null' | 'str' | 'str_array' | 'int' | 'int_array' | 'binary_data' | 'timestamp';
      }
      export interface TagFamilyForWrite {
        tags?: banyandb.model.v1.TagValue[];
      }
      export interface FieldValue {
        null?: google.protobuf.NullValue;
        str?: banyandb.model.v1.Str;
        int?: banyandb.model.v1.Int;
        binary_data?: Buffer;
        float?: banyandb.model.v1.Float;
        value?: 'null' | 'str' | 'int' | 'binary_data' | 'float';
      }
      export type AggregationFunction = 'AGGREGATION_FUNCTION_UNSPECIFIED' | 'AGGREGATION_FUNCTION_MEAN' | 'AGGREGATION_FUNCTION_MAX' | 'AGGREGATION_FUNCTION_MIN' | 'AGGREGATION_FUNCTION_COUNT' | 'AGGREGATION_FUNCTION_SUM';
      export interface Tag {
        key?: string;
        value?: banyandb.model.v1.TagValue;
      }
      export interface TagFamily {
        name?: string;
        tags?: banyandb.model.v1.Tag[];
      }
      export interface Condition {
        name?: string;
        op?: banyandb.model.v1.Condition.BinaryOp;
        value?: banyandb.model.v1.TagValue;
        match_option?: banyandb.model.v1.Condition.MatchOption;
      }
      export namespace Condition {
        export type BinaryOp = 'BINARY_OP_UNSPECIFIED' | 'BINARY_OP_EQ' | 'BINARY_OP_NE' | 'BINARY_OP_LT' | 'BINARY_OP_GT' | 'BINARY_OP_LE' | 'BINARY_OP_GE' | 'BINARY_OP_HAVING' | 'BINARY_OP_NOT_HAVING' | 'BINARY_OP_IN' | 'BINARY_OP_NOT_IN' | 'BINARY_OP_MATCH';
        export interface MatchOption {
          analyzer?: string;
          operator?: banyandb.model.v1.Condition.MatchOption.Operator;
        }
        export namespace MatchOption {
          export type Operator = 'OPERATOR_UNSPECIFIED' | 'OPERATOR_AND' | 'OPERATOR_OR';
        }
      }
      export interface Criteria {
        le?: banyandb.model.v1.LogicalExpression;
        condition?: banyandb.model.v1.Condition;
        exp?: 'le' | 'condition';
      }
      export interface LogicalExpression {
        op?: banyandb.model.v1.LogicalExpression.LogicalOp;
        left?: banyandb.model.v1.Criteria;
        right?: banyandb.model.v1.Criteria;
      }
      export namespace LogicalExpression {
        export type LogicalOp = 'LOGICAL_OP_UNSPECIFIED' | 'LOGICAL_OP_AND' | 'LOGICAL_OP_OR';
      }
      export type Sort = 'SORT_UNSPECIFIED' | 'SORT_DESC' | 'SORT_ASC';
      export interface QueryOrder {
        index_rule_name?: string;
        sort?: banyandb.model.v1.Sort;
      }
      export interface TagProjection {
        tag_families?: banyandb.model.v1.TagProjection.TagFamily[];
      }
      export namespace TagProjection {
        export interface TagFamily {
          name?: string;
          tags?: string[];
        }
      }
      export interface TimeRange {
        begin?: google.protobuf.Timestamp;
        end?: google.protobuf.Timestamp;
      }
      export type Status = 'STATUS_UNSPECIFIED' | 'STATUS_SUCCEED' | 'STATUS_INVALID_TIMESTAMP' | 'STATUS_NOT_FOUND' | 'STATUS_EXPIRED_SCHEMA' | 'STATUS_INTERNAL_ERROR' | 'STATUS_DISK_FULL' | 'STATUS_VERSION_UNSUPPORTED' | 'STATUS_VERSION_DEPRECATED' | 'STATUS_METADATA_REQUIRED';
    }
  }
  export namespace database {
    export namespace v1 {
      export type TagType = 'TAG_TYPE_UNSPECIFIED' | 'TAG_TYPE_STRING' | 'TAG_TYPE_INT' | 'TAG_TYPE_STRING_ARRAY' | 'TAG_TYPE_INT_ARRAY' | 'TAG_TYPE_DATA_BINARY' | 'TAG_TYPE_TIMESTAMP';
      export interface TagFamilySpec {
        name?: string;
        tags?: banyandb.database.v1.TagSpec[];
      }
      export interface TagSpec {
        name?: string;
        type?: banyandb.database.v1.TagType;
      }
      export interface Stream {
        metadata?: banyandb.common.v1.Metadata;
        tag_families?: banyandb.database.v1.TagFamilySpec[];
        entity?: banyandb.database.v1.Entity;
        updated_at?: google.protobuf.Timestamp;
      }
      export interface Entity {
        tag_names?: string[];
      }
      export interface ShardingKey {
        tag_names?: string[];
      }
      export type FieldType = 'FIELD_TYPE_UNSPECIFIED' | 'FIELD_TYPE_STRING' | 'FIELD_TYPE_INT' | 'FIELD_TYPE_DATA_BINARY' | 'FIELD_TYPE_FLOAT';
      export type EncodingMethod = 'ENCODING_METHOD_UNSPECIFIED' | 'ENCODING_METHOD_GORILLA';
      export type CompressionMethod = 'COMPRESSION_METHOD_UNSPECIFIED' | 'COMPRESSION_METHOD_ZSTD';
      export interface FieldSpec {
        name?: string;
        field_type?: banyandb.database.v1.FieldType;
        encoding_method?: banyandb.database.v1.EncodingMethod;
        compression_method?: banyandb.database.v1.CompressionMethod;
      }
      export interface Measure {
        metadata?: banyandb.common.v1.Metadata;
        tag_families?: banyandb.database.v1.TagFamilySpec[];
        fields?: banyandb.database.v1.FieldSpec[];
        entity?: banyandb.database.v1.Entity;
        interval?: string;
        updated_at?: google.protobuf.Timestamp;
        index_mode?: boolean;
        sharding_key?: banyandb.database.v1.ShardingKey;
      }
      export interface TopNAggregation {
        metadata?: banyandb.common.v1.Metadata;
        source_measure?: banyandb.common.v1.Metadata;
        field_name?: string;
        field_value_sort?: banyandb.model.v1.Sort;
        group_by_tag_names?: string[];
        criteria?: banyandb.model.v1.Criteria;
        counters_number?: number;
        lru_size?: number;
        updated_at?: google.protobuf.Timestamp;
      }
      export interface IndexRule {
        metadata?: banyandb.common.v1.Metadata;
        tags?: string[];
        type?: banyandb.database.v1.IndexRule.Type;
        updated_at?: google.protobuf.Timestamp;
        analyzer?: string;
        no_sort?: boolean;
      }
      export namespace IndexRule {
        export type Type = 'TYPE_UNSPECIFIED' | 'TYPE_INVERTED' | 'TYPE_SKIPPING' | 'TYPE_TREE';
      }
      export interface Subject {
        catalog?: banyandb.common.v1.Catalog;
        name?: string;
      }
      export interface IndexRuleBinding {
        metadata?: banyandb.common.v1.Metadata;
        rules?: string[];
        subject?: banyandb.database.v1.Subject;
        begin_at?: google.protobuf.Timestamp;
        expire_at?: google.protobuf.Timestamp;
        updated_at?: google.protobuf.Timestamp;
      }
      export interface Property {
        metadata?: banyandb.common.v1.Metadata;
        tags?: banyandb.database.v1.TagSpec[];
        updated_at?: google.protobuf.Timestamp;
      }
      export interface TraceTagSpec {
        name?: string;
        type?: banyandb.database.v1.TagType;
      }
      export interface Trace {
        metadata?: banyandb.common.v1.Metadata;
        tags?: banyandb.database.v1.TraceTagSpec[];
        trace_id_tag_name?: string;
        timestamp_tag_name?: string;
        updated_at?: google.protobuf.Timestamp;
        span_id_tag_name?: string;
      }
      export interface StreamRegistryServiceCreateRequest {
        stream?: banyandb.database.v1.Stream;
      }
      export interface StreamRegistryServiceCreateResponse {
        mod_revision?: string;
      }
      export interface StreamRegistryServiceUpdateRequest {
        stream?: banyandb.database.v1.Stream;
      }
      export interface StreamRegistryServiceUpdateResponse {
        mod_revision?: string;
      }
      export interface StreamRegistryServiceDeleteRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface StreamRegistryServiceDeleteResponse {
        deleted?: boolean;
      }
      export interface StreamRegistryServiceGetRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface StreamRegistryServiceGetResponse {
        stream?: banyandb.database.v1.Stream;
      }
      export interface StreamRegistryServiceExistRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface StreamRegistryServiceExistResponse {
        has_group?: boolean;
        has_stream?: boolean;
      }
      export interface StreamRegistryServiceListRequest {
        group?: string;
      }
      export interface StreamRegistryServiceListResponse {
        stream?: banyandb.database.v1.Stream[];
      }
      export interface IndexRuleBindingRegistryServiceCreateRequest {
        index_rule_binding?: banyandb.database.v1.IndexRuleBinding;
      }
      export interface IndexRuleBindingRegistryServiceCreateResponse {
      }
      export interface IndexRuleBindingRegistryServiceUpdateRequest {
        index_rule_binding?: banyandb.database.v1.IndexRuleBinding;
      }
      export interface IndexRuleBindingRegistryServiceUpdateResponse {
      }
      export interface IndexRuleBindingRegistryServiceDeleteRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface IndexRuleBindingRegistryServiceDeleteResponse {
        deleted?: boolean;
      }
      export interface IndexRuleBindingRegistryServiceGetRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface IndexRuleBindingRegistryServiceGetResponse {
        index_rule_binding?: banyandb.database.v1.IndexRuleBinding;
      }
      export interface IndexRuleBindingRegistryServiceListRequest {
        group?: string;
      }
      export interface IndexRuleBindingRegistryServiceListResponse {
        index_rule_binding?: banyandb.database.v1.IndexRuleBinding[];
      }
      export interface IndexRuleBindingRegistryServiceExistRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface IndexRuleBindingRegistryServiceExistResponse {
        has_group?: boolean;
        has_index_rule_binding?: boolean;
      }
      export interface IndexRuleRegistryServiceCreateRequest {
        index_rule?: banyandb.database.v1.IndexRule;
      }
      export interface IndexRuleRegistryServiceCreateResponse {
      }
      export interface IndexRuleRegistryServiceUpdateRequest {
        index_rule?: banyandb.database.v1.IndexRule;
      }
      export interface IndexRuleRegistryServiceUpdateResponse {
      }
      export interface IndexRuleRegistryServiceDeleteRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface IndexRuleRegistryServiceDeleteResponse {
        deleted?: boolean;
      }
      export interface IndexRuleRegistryServiceGetRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface IndexRuleRegistryServiceGetResponse {
        index_rule?: banyandb.database.v1.IndexRule;
      }
      export interface IndexRuleRegistryServiceListRequest {
        group?: string;
      }
      export interface IndexRuleRegistryServiceListResponse {
        index_rule?: banyandb.database.v1.IndexRule[];
      }
      export interface IndexRuleRegistryServiceExistRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface IndexRuleRegistryServiceExistResponse {
        has_group?: boolean;
        has_index_rule?: boolean;
      }
      export interface MeasureRegistryServiceCreateRequest {
        measure?: banyandb.database.v1.Measure;
      }
      export interface MeasureRegistryServiceCreateResponse {
        mod_revision?: string;
      }
      export interface MeasureRegistryServiceUpdateRequest {
        measure?: banyandb.database.v1.Measure;
      }
      export interface MeasureRegistryServiceUpdateResponse {
        mod_revision?: string;
      }
      export interface MeasureRegistryServiceDeleteRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface MeasureRegistryServiceDeleteResponse {
        deleted?: boolean;
      }
      export interface MeasureRegistryServiceGetRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface MeasureRegistryServiceGetResponse {
        measure?: banyandb.database.v1.Measure;
      }
      export interface MeasureRegistryServiceListRequest {
        group?: string;
      }
      export interface MeasureRegistryServiceListResponse {
        measure?: banyandb.database.v1.Measure[];
      }
      export interface MeasureRegistryServiceExistRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface MeasureRegistryServiceExistResponse {
        has_group?: boolean;
        has_measure?: boolean;
      }
      export interface GroupRegistryServiceCreateRequest {
        group?: banyandb.common.v1.Group;
      }
      export interface GroupRegistryServiceCreateResponse {
      }
      export interface GroupRegistryServiceUpdateRequest {
        group?: banyandb.common.v1.Group;
      }
      export interface GroupRegistryServiceUpdateResponse {
      }
      export interface GroupRegistryServiceDeleteRequest {
        group?: string;
      }
      export interface GroupRegistryServiceDeleteResponse {
        deleted?: boolean;
      }
      export interface GroupRegistryServiceGetRequest {
        group?: string;
      }
      export interface GroupRegistryServiceGetResponse {
        group?: banyandb.common.v1.Group;
      }
      export interface GroupRegistryServiceListRequest {
      }
      export interface GroupRegistryServiceListResponse {
        group?: banyandb.common.v1.Group[];
      }
      export interface GroupRegistryServiceExistRequest {
        group?: string;
      }
      export interface GroupRegistryServiceExistResponse {
        has_group?: boolean;
      }
      export interface TopNAggregationRegistryServiceCreateRequest {
        top_n_aggregation?: banyandb.database.v1.TopNAggregation;
      }
      export interface TopNAggregationRegistryServiceCreateResponse {
      }
      export interface TopNAggregationRegistryServiceUpdateRequest {
        top_n_aggregation?: banyandb.database.v1.TopNAggregation;
      }
      export interface TopNAggregationRegistryServiceUpdateResponse {
      }
      export interface TopNAggregationRegistryServiceDeleteRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface TopNAggregationRegistryServiceDeleteResponse {
        deleted?: boolean;
      }
      export interface TopNAggregationRegistryServiceGetRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface TopNAggregationRegistryServiceGetResponse {
        top_n_aggregation?: banyandb.database.v1.TopNAggregation;
      }
      export interface TopNAggregationRegistryServiceListRequest {
        group?: string;
      }
      export interface TopNAggregationRegistryServiceListResponse {
        top_n_aggregation?: banyandb.database.v1.TopNAggregation[];
      }
      export interface TopNAggregationRegistryServiceExistRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface TopNAggregationRegistryServiceExistResponse {
        has_group?: boolean;
        has_top_n_aggregation?: boolean;
      }
      export interface SnapshotRequest {
        groups?: banyandb.database.v1.SnapshotRequest.Group[];
      }
      export namespace SnapshotRequest {
        export interface Group {
          catalog?: banyandb.common.v1.Catalog;
          group?: string;
        }
      }
      export interface Snapshot {
        catalog?: banyandb.common.v1.Catalog;
        name?: string;
        error?: string;
      }
      export interface SnapshotResponse {
        snapshots?: banyandb.database.v1.Snapshot[];
      }
      export interface PropertyRegistryServiceCreateRequest {
        property?: banyandb.database.v1.Property;
      }
      export interface PropertyRegistryServiceCreateResponse {
        mod_revision?: string;
      }
      export interface PropertyRegistryServiceUpdateRequest {
        property?: banyandb.database.v1.Property;
      }
      export interface PropertyRegistryServiceUpdateResponse {
        mod_revision?: string;
      }
      export interface PropertyRegistryServiceDeleteRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface PropertyRegistryServiceDeleteResponse {
        deleted?: boolean;
      }
      export interface PropertyRegistryServiceGetRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface PropertyRegistryServiceGetResponse {
        property?: banyandb.database.v1.Property;
      }
      export interface PropertyRegistryServiceListRequest {
        group?: string;
      }
      export interface PropertyRegistryServiceListResponse {
        properties?: banyandb.database.v1.Property[];
      }
      export interface PropertyRegistryServiceExistRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface PropertyRegistryServiceExistResponse {
        has_group?: boolean;
        has_property?: boolean;
      }
      export interface TraceRegistryServiceCreateRequest {
        trace?: banyandb.database.v1.Trace;
      }
      export interface TraceRegistryServiceCreateResponse {
        mod_revision?: string;
      }
      export interface TraceRegistryServiceUpdateRequest {
        trace?: banyandb.database.v1.Trace;
      }
      export interface TraceRegistryServiceUpdateResponse {
        mod_revision?: string;
      }
      export interface TraceRegistryServiceDeleteRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface TraceRegistryServiceDeleteResponse {
        deleted?: boolean;
      }
      export interface TraceRegistryServiceGetRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface TraceRegistryServiceGetResponse {
        trace?: banyandb.database.v1.Trace;
      }
      export interface TraceRegistryServiceExistRequest {
        metadata?: banyandb.common.v1.Metadata;
      }
      export interface TraceRegistryServiceExistResponse {
        has_group?: boolean;
        has_trace?: boolean;
      }
      export interface TraceRegistryServiceListRequest {
        group?: string;
      }
      export interface TraceRegistryServiceListResponse {
        trace?: banyandb.database.v1.Trace[];
      }
    }
  }
  export namespace stream {
    export namespace v1 {
      export interface Element {
        element_id?: string;
        timestamp?: google.protobuf.Timestamp;
        tag_families?: banyandb.model.v1.TagFamily[];
      }
      export interface QueryResponse {
        elements?: banyandb.stream.v1.Element[];
        trace?: banyandb.common.v1.Trace;
      }
      export interface QueryRequest {
        groups?: string[];
        name?: string;
        time_range?: banyandb.model.v1.TimeRange;
        offset?: number;
        limit?: number;
        order_by?: banyandb.model.v1.QueryOrder;
        criteria?: banyandb.model.v1.Criteria;
        projection?: banyandb.model.v1.TagProjection;
        trace?: boolean;
        stages?: string[];
      }
      export interface TagFamilySpec {
        name?: string;
        tag_names?: string[];
      }
      export interface ElementValue {
        element_id?: string;
        timestamp?: google.protobuf.Timestamp;
        tag_families?: banyandb.model.v1.TagFamilyForWrite[];
      }
      export interface WriteRequest {
        metadata?: banyandb.common.v1.Metadata;
        element?: banyandb.stream.v1.ElementValue;
        message_id?: string;
        tag_family_spec?: banyandb.stream.v1.TagFamilySpec[];
      }
      export interface WriteResponse {
        message_id?: string;
        status?: string;
        metadata?: banyandb.common.v1.Metadata;
      }
    }
  }
  export namespace measure {
    export namespace v1 {
      export interface DataPoint {
        timestamp?: google.protobuf.Timestamp;
        tag_families?: banyandb.model.v1.TagFamily[];
        fields?: banyandb.measure.v1.DataPoint.Field[];
        sid?: string;
        version?: string;
      }
      export namespace DataPoint {
        export interface Field {
          name?: string;
          value?: banyandb.model.v1.FieldValue;
        }
      }
      export interface QueryResponse {
        data_points?: banyandb.measure.v1.DataPoint[];
        trace?: banyandb.common.v1.Trace;
      }
      export interface QueryRequest {
        groups?: string[];
        name?: string;
        time_range?: banyandb.model.v1.TimeRange;
        criteria?: banyandb.model.v1.Criteria;
        tag_projection?: banyandb.model.v1.TagProjection;
        field_projection?: banyandb.measure.v1.QueryRequest.FieldProjection;
        group_by?: banyandb.measure.v1.QueryRequest.GroupBy;
        agg?: banyandb.measure.v1.QueryRequest.Aggregation;
        top?: banyandb.measure.v1.QueryRequest.Top;
        offset?: number;
        limit?: number;
        order_by?: banyandb.model.v1.QueryOrder;
        trace?: boolean;
        stages?: string[];
        rewrite_agg_top_n_result?: boolean;
      }
      export namespace QueryRequest {
        export interface FieldProjection {
          names?: string[];
        }
        export interface GroupBy {
          tag_projection?: banyandb.model.v1.TagProjection;
          field_name?: string;
        }
        export interface Aggregation {
          function?: banyandb.model.v1.AggregationFunction;
          field_name?: string;
        }
        export interface Top {
          number?: number;
          field_name?: string;
          field_value_sort?: banyandb.model.v1.Sort;
        }
      }
      export interface TopNList {
        timestamp?: google.protobuf.Timestamp;
        items?: banyandb.measure.v1.TopNList.Item[];
      }
      export namespace TopNList {
        export interface Item {
          entity?: banyandb.model.v1.Tag[];
          value?: banyandb.model.v1.FieldValue;
        }
      }
      export interface TopNResponse {
        lists?: banyandb.measure.v1.TopNList[];
        trace?: banyandb.common.v1.Trace;
      }
      export interface TopNRequest {
        groups?: string[];
        name?: string;
        time_range?: banyandb.model.v1.TimeRange;
        top_n?: number;
        agg?: banyandb.model.v1.AggregationFunction;
        conditions?: banyandb.model.v1.Condition[];
        field_value_sort?: banyandb.model.v1.Sort;
        trace?: boolean;
        stages?: string[];
      }
      export interface TagFamilySpec {
        name?: string;
        tag_names?: string[];
      }
      export interface DataPointSpec {
        tag_family_spec?: banyandb.measure.v1.TagFamilySpec[];
        field_names?: string[];
      }
      export interface DataPointValue {
        timestamp?: google.protobuf.Timestamp;
        tag_families?: banyandb.model.v1.TagFamilyForWrite[];
        fields?: banyandb.model.v1.FieldValue[];
        version?: string;
      }
      export interface WriteRequest {
        metadata?: banyandb.common.v1.Metadata;
        data_point?: banyandb.measure.v1.DataPointValue;
        message_id?: string;
        data_point_spec?: banyandb.measure.v1.DataPointSpec;
      }
      export interface WriteResponse {
        message_id?: string;
        status?: string;
        metadata?: banyandb.common.v1.Metadata;
      }
    }
  }
}
export namespace google {
  export namespace protobuf {
      export type NullValue = 'NULL_VALUE';
      export interface Timestamp {
        seconds?: string;
        nanos?: number;
      }
  }
}
