/**
 * GENERATED by `pnpm proto:sync` from the vendored .proto in ./proto — DO NOT EDIT.
 * `pnpm proto:check` regenerates this file and fails on any diff.
 *
 * Types only. These describe what @grpc/proto-loader returns under the options
 * in ./proto.ts (keepCase, longs: String, enums: String, oneofs: true) — see
 * scripts/gen-proto-types.mjs.
 */

export namespace banyandb {
  export namespace common {
    export namespace v1 {
      export type Catalog = 'CATALOG_UNSPECIFIED' | 'CATALOG_STREAM' | 'CATALOG_MEASURE' | 'CATALOG_PROPERTY' | 'CATALOG_TRACE';
      export interface Metadata {
        group?: string;
        name?: string;
        id?: number;
        create_revision?: string;
        mod_revision?: string;
      }
      export interface IntervalRule {
        unit?: banyandb.common.v1.IntervalRule.Unit;
        num?: number;
      }
      export namespace IntervalRule {
        export type Unit = 'UNIT_UNSPECIFIED' | 'UNIT_HOUR' | 'UNIT_DAY';
      }
      export interface LifecycleStage {
        name?: string;
        shard_num?: number;
        segment_interval?: banyandb.common.v1.IntervalRule | null;
        ttl?: banyandb.common.v1.IntervalRule | null;
        node_selector?: string;
        close?: boolean;
        replicas?: number;
      }
      export interface ResourceOpts {
        shard_num?: number;
        segment_interval?: banyandb.common.v1.IntervalRule | null;
        ttl?: banyandb.common.v1.IntervalRule | null;
        stages?: banyandb.common.v1.LifecycleStage[];
        default_stages?: string[];
        replicas?: number;
      }
      export type PipelineEvent = 'PIPELINE_EVENT_UNSPECIFIED' | 'PIPELINE_EVENT_MERGE' | 'PIPELINE_EVENT_FINALIZE';
      export interface SamplerPlugin {
        path?: string;
        symbol?: string;
        abi_version?: number;
        config?: google.protobuf.Struct | null;
      }
      export interface Plugin {
        name?: string;
        sampler?: banyandb.common.v1.SamplerPlugin | null;
        kind?: 'sampler';
      }
      export interface StageRule {
        stage?: string;
        plugins?: banyandb.common.v1.Plugin[];
      }
      export interface TracePipelineConfig {
        enabled?: boolean;
        plugins?: banyandb.common.v1.Plugin[];
        merge_grace?: google.protobuf.Duration | null;
        finalize_grace?: google.protobuf.Duration | null;
        stages?: banyandb.common.v1.StageRule[];
        schema_names?: string[];
        schema_name_regex?: string;
        enabled_events?: banyandb.common.v1.PipelineEvent[];
      }
      export interface Group {
        metadata?: banyandb.common.v1.Metadata | null;
        catalog?: banyandb.common.v1.Catalog;
        resource_opts?: banyandb.common.v1.ResourceOpts | null;
        updated_at?: google.protobuf.Timestamp | null;
        created_at?: google.protobuf.Timestamp | null;
        pipeline?: banyandb.common.v1.TracePipelineConfig | null;
        _pipeline?: 'pipeline';
      }
      export interface APIVersion {
        version?: string;
        revision?: string;
      }
      export interface GetAPIVersionRequest {
      }
      export interface GetAPIVersionResponse {
        version?: banyandb.common.v1.APIVersion | null;
      }
      export interface Trace {
        trace_id?: string;
        spans?: banyandb.common.v1.Span[];
        error?: boolean;
      }
      export interface Span {
        start_time?: google.protobuf.Timestamp | null;
        end_time?: google.protobuf.Timestamp | null;
        error?: boolean;
        tags?: banyandb.common.v1.Tag[];
        message?: string;
        children?: banyandb.common.v1.Span[];
        duration?: string;
      }
      export interface Tag {
        key?: string;
        value?: string;
      }
    }
  }
  export namespace model {
    export namespace v1 {
      export interface Str {
        value?: string;
      }
      export interface Int {
        value?: string;
      }
      export interface Float {
        value?: number;
      }
      export interface StrArray {
        value?: string[];
      }
      export interface IntArray {
        value?: string[];
      }
      export interface TagValue {
        null?: google.protobuf.NullValue;
        str?: banyandb.model.v1.Str | null;
        str_array?: banyandb.model.v1.StrArray | null;
        int?: banyandb.model.v1.Int | null;
        int_array?: banyandb.model.v1.IntArray | null;
        binary_data?: Buffer;
        timestamp?: google.protobuf.Timestamp | null;
        value?: 'null' | 'str' | 'str_array' | 'int' | 'int_array' | 'binary_data' | 'timestamp';
      }
      export interface TagFamilyForWrite {
        tags?: banyandb.model.v1.TagValue[];
      }
      export interface FieldValue {
        null?: google.protobuf.NullValue;
        str?: banyandb.model.v1.Str | null;
        int?: banyandb.model.v1.Int | null;
        binary_data?: Buffer;
        float?: banyandb.model.v1.Float | null;
        value?: 'null' | 'str' | 'int' | 'binary_data' | 'float';
      }
      export type AggregationFunction = 'AGGREGATION_FUNCTION_UNSPECIFIED' | 'AGGREGATION_FUNCTION_MEAN' | 'AGGREGATION_FUNCTION_MAX' | 'AGGREGATION_FUNCTION_MIN' | 'AGGREGATION_FUNCTION_COUNT' | 'AGGREGATION_FUNCTION_SUM';
      export interface Tag {
        key?: string;
        value?: banyandb.model.v1.TagValue | null;
      }
      export interface TagFamily {
        name?: string;
        tags?: banyandb.model.v1.Tag[];
      }
      export interface Condition {
        name?: string;
        op?: banyandb.model.v1.Condition.BinaryOp;
        value?: banyandb.model.v1.TagValue | null;
        match_option?: banyandb.model.v1.Condition.MatchOption | null;
      }
      export namespace Condition {
        export type BinaryOp = 'BINARY_OP_UNSPECIFIED' | 'BINARY_OP_EQ' | 'BINARY_OP_NE' | 'BINARY_OP_LT' | 'BINARY_OP_GT' | 'BINARY_OP_LE' | 'BINARY_OP_GE' | 'BINARY_OP_HAVING' | 'BINARY_OP_NOT_HAVING' | 'BINARY_OP_IN' | 'BINARY_OP_NOT_IN' | 'BINARY_OP_MATCH';
        export interface MatchOption {
          analyzer?: string;
          operator?: banyandb.model.v1.Condition.MatchOption.Operator;
        }
        export namespace MatchOption {
          export type Operator = 'OPERATOR_UNSPECIFIED' | 'OPERATOR_AND' | 'OPERATOR_OR';
        }
      }
      export interface Criteria {
        le?: banyandb.model.v1.LogicalExpression | null;
        condition?: banyandb.model.v1.Condition | null;
        exp?: 'le' | 'condition';
      }
      export interface LogicalExpression {
        op?: banyandb.model.v1.LogicalExpression.LogicalOp;
        left?: banyandb.model.v1.Criteria | null;
        right?: banyandb.model.v1.Criteria | null;
      }
      export namespace LogicalExpression {
        export type LogicalOp = 'LOGICAL_OP_UNSPECIFIED' | 'LOGICAL_OP_AND' | 'LOGICAL_OP_OR';
      }
      export type Sort = 'SORT_UNSPECIFIED' | 'SORT_DESC' | 'SORT_ASC';
      export interface QueryOrder {
        index_rule_name?: string;
        sort?: banyandb.model.v1.Sort;
      }
      export interface TagProjection {
        tag_families?: banyandb.model.v1.TagProjection.TagFamily[];
      }
      export namespace TagProjection {
        export interface TagFamily {
          name?: string;
          tags?: string[];
        }
      }
      export interface TimeRange {
        begin?: google.protobuf.Timestamp | null;
        end?: google.protobuf.Timestamp | null;
      }
      export type Status = 'STATUS_UNSPECIFIED' | 'STATUS_SUCCEED' | 'STATUS_INVALID_TIMESTAMP' | 'STATUS_NOT_FOUND' | 'STATUS_EXPIRED_SCHEMA' | 'STATUS_INTERNAL_ERROR' | 'STATUS_DISK_FULL' | 'STATUS_VERSION_UNSUPPORTED' | 'STATUS_VERSION_DEPRECATED' | 'STATUS_METADATA_REQUIRED' | 'STATUS_SCHEMA_NOT_APPLIED';
    }
  }
  export namespace database {
    export namespace v1 {
      export type Role = 'ROLE_UNSPECIFIED' | 'ROLE_META' | 'ROLE_DATA' | 'ROLE_LIAISON';
      export interface Node {
        metadata?: banyandb.common.v1.Metadata | null;
        roles?: banyandb.database.v1.Role[];
        grpc_address?: string;
        http_address?: string;
        created_at?: google.protobuf.Timestamp | null;
        labels?: Partial<Record<string, string>>;
        property_repair_gossip_grpc_address?: string;
        property_schema_grpc_address?: string;
        property_schema_gossip_grpc_address?: string;
      }
      export interface Shard {
        id?: string;
        metadata?: banyandb.common.v1.Metadata | null;
        catalog?: banyandb.common.v1.Catalog;
        node?: string;
        total?: number;
        updated_at?: google.protobuf.Timestamp | null;
        created_at?: google.protobuf.Timestamp | null;
      }
      export type TagType = 'TAG_TYPE_UNSPECIFIED' | 'TAG_TYPE_STRING' | 'TAG_TYPE_INT' | 'TAG_TYPE_STRING_ARRAY' | 'TAG_TYPE_INT_ARRAY' | 'TAG_TYPE_DATA_BINARY' | 'TAG_TYPE_TIMESTAMP';
      export interface TagFamilySpec {
        name?: string;
        tags?: banyandb.database.v1.TagSpec[];
      }
      export interface TagSpec {
        name?: string;
        type?: banyandb.database.v1.TagType;
      }
      export interface Stream {
        metadata?: banyandb.common.v1.Metadata | null;
        tag_families?: banyandb.database.v1.TagFamilySpec[];
        entity?: banyandb.database.v1.Entity | null;
        updated_at?: google.protobuf.Timestamp | null;
        created_at?: google.protobuf.Timestamp | null;
      }
      export interface Entity {
        tag_names?: string[];
      }
      export interface ShardingKey {
        tag_names?: string[];
      }
      export type FieldType = 'FIELD_TYPE_UNSPECIFIED' | 'FIELD_TYPE_STRING' | 'FIELD_TYPE_INT' | 'FIELD_TYPE_DATA_BINARY' | 'FIELD_TYPE_FLOAT';
      export type EncodingMethod = 'ENCODING_METHOD_UNSPECIFIED' | 'ENCODING_METHOD_GORILLA';
      export type CompressionMethod = 'COMPRESSION_METHOD_UNSPECIFIED' | 'COMPRESSION_METHOD_ZSTD';
      export interface FieldSpec {
        name?: string;
        field_type?: banyandb.database.v1.FieldType;
        encoding_method?: banyandb.database.v1.EncodingMethod;
        compression_method?: banyandb.database.v1.CompressionMethod;
      }
      export interface Measure {
        metadata?: banyandb.common.v1.Metadata | null;
        tag_families?: banyandb.database.v1.TagFamilySpec[];
        fields?: banyandb.database.v1.FieldSpec[];
        entity?: banyandb.database.v1.Entity | null;
        interval?: string;
        updated_at?: google.protobuf.Timestamp | null;
        index_mode?: boolean;
        sharding_key?: banyandb.database.v1.ShardingKey | null;
        created_at?: google.protobuf.Timestamp | null;
      }
      export interface TopNAggregation {
        metadata?: banyandb.common.v1.Metadata | null;
        source_measure?: banyandb.common.v1.Metadata | null;
        field_name?: string;
        field_value_sort?: banyandb.model.v1.Sort;
        group_by_tag_names?: string[];
        criteria?: banyandb.model.v1.Criteria | null;
        counters_number?: number;
        lru_size?: number;
        updated_at?: google.protobuf.Timestamp | null;
        created_at?: google.protobuf.Timestamp | null;
      }
      export interface IndexRule {
        metadata?: banyandb.common.v1.Metadata | null;
        tags?: string[];
        type?: banyandb.database.v1.IndexRule.Type;
        updated_at?: google.protobuf.Timestamp | null;
        analyzer?: string;
        no_sort?: boolean;
        created_at?: google.protobuf.Timestamp | null;
      }
      export namespace IndexRule {
        export type Type = 'TYPE_UNSPECIFIED' | 'TYPE_INVERTED' | 'TYPE_SKIPPING' | 'TYPE_TREE';
      }
      export interface Subject {
        catalog?: banyandb.common.v1.Catalog;
        name?: string;
      }
      export interface IndexRuleBinding {
        metadata?: banyandb.common.v1.Metadata | null;
        rules?: string[];
        subject?: banyandb.database.v1.Subject | null;
        begin_at?: google.protobuf.Timestamp | null;
        expire_at?: google.protobuf.Timestamp | null;
        updated_at?: google.protobuf.Timestamp | null;
        created_at?: google.protobuf.Timestamp | null;
      }
      export interface Property {
        metadata?: banyandb.common.v1.Metadata | null;
        tags?: banyandb.database.v1.TagSpec[];
        updated_at?: google.protobuf.Timestamp | null;
        created_at?: google.protobuf.Timestamp | null;
      }
      export interface TraceTagSpec {
        name?: string;
        type?: banyandb.database.v1.TagType;
      }
      export interface Trace {
        metadata?: banyandb.common.v1.Metadata | null;
        tags?: banyandb.database.v1.TraceTagSpec[];
        trace_id_tag_name?: string;
        timestamp_tag_name?: string;
        updated_at?: google.protobuf.Timestamp | null;
        span_id_tag_name?: string;
        created_at?: google.protobuf.Timestamp | null;
      }
      export interface StreamRegistryServiceCreateRequest {
        stream?: banyandb.database.v1.Stream | null;
      }
      export interface StreamRegistryServiceCreateResponse {
        mod_revision?: string;
      }
      export interface StreamRegistryServiceUpdateRequest {
        stream?: banyandb.database.v1.Stream | null;
      }
      export interface StreamRegistryServiceUpdateResponse {
        mod_revision?: string;
      }
      export interface StreamRegistryServiceDeleteRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface StreamRegistryServiceDeleteResponse {
        deleted?: boolean;
        delete_time?: string;
        mod_revision?: string;
      }
      export interface StreamRegistryServiceGetRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface StreamRegistryServiceGetResponse {
        stream?: banyandb.database.v1.Stream | null;
      }
      export interface StreamRegistryServiceExistRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface StreamRegistryServiceExistResponse {
        has_group?: boolean;
        has_stream?: boolean;
      }
      export interface StreamRegistryServiceListRequest {
        group?: string;
      }
      export interface StreamRegistryServiceListResponse {
        stream?: banyandb.database.v1.Stream[];
      }
      export interface IndexRuleBindingRegistryServiceCreateRequest {
        index_rule_binding?: banyandb.database.v1.IndexRuleBinding | null;
      }
      export interface IndexRuleBindingRegistryServiceCreateResponse {
        mod_revision?: string;
      }
      export interface IndexRuleBindingRegistryServiceUpdateRequest {
        index_rule_binding?: banyandb.database.v1.IndexRuleBinding | null;
      }
      export interface IndexRuleBindingRegistryServiceUpdateResponse {
        mod_revision?: string;
      }
      export interface IndexRuleBindingRegistryServiceDeleteRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface IndexRuleBindingRegistryServiceDeleteResponse {
        deleted?: boolean;
        delete_time?: string;
        mod_revision?: string;
      }
      export interface IndexRuleBindingRegistryServiceGetRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface IndexRuleBindingRegistryServiceGetResponse {
        index_rule_binding?: banyandb.database.v1.IndexRuleBinding | null;
      }
      export interface IndexRuleBindingRegistryServiceListRequest {
        group?: string;
      }
      export interface IndexRuleBindingRegistryServiceListResponse {
        index_rule_binding?: banyandb.database.v1.IndexRuleBinding[];
      }
      export interface IndexRuleBindingRegistryServiceExistRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface IndexRuleBindingRegistryServiceExistResponse {
        has_group?: boolean;
        has_index_rule_binding?: boolean;
      }
      export interface IndexRuleRegistryServiceCreateRequest {
        index_rule?: banyandb.database.v1.IndexRule | null;
      }
      export interface IndexRuleRegistryServiceCreateResponse {
        mod_revision?: string;
      }
      export interface IndexRuleRegistryServiceUpdateRequest {
        index_rule?: banyandb.database.v1.IndexRule | null;
      }
      export interface IndexRuleRegistryServiceUpdateResponse {
        mod_revision?: string;
      }
      export interface IndexRuleRegistryServiceDeleteRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface IndexRuleRegistryServiceDeleteResponse {
        deleted?: boolean;
        delete_time?: string;
        mod_revision?: string;
      }
      export interface IndexRuleRegistryServiceGetRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface IndexRuleRegistryServiceGetResponse {
        index_rule?: banyandb.database.v1.IndexRule | null;
      }
      export interface IndexRuleRegistryServiceListRequest {
        group?: string;
      }
      export interface IndexRuleRegistryServiceListResponse {
        index_rule?: banyandb.database.v1.IndexRule[];
      }
      export interface IndexRuleRegistryServiceExistRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface IndexRuleRegistryServiceExistResponse {
        has_group?: boolean;
        has_index_rule?: boolean;
      }
      export interface MeasureRegistryServiceCreateRequest {
        measure?: banyandb.database.v1.Measure | null;
      }
      export interface MeasureRegistryServiceCreateResponse {
        mod_revision?: string;
      }
      export interface MeasureRegistryServiceUpdateRequest {
        measure?: banyandb.database.v1.Measure | null;
      }
      export interface MeasureRegistryServiceUpdateResponse {
        mod_revision?: string;
      }
      export interface MeasureRegistryServiceDeleteRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface MeasureRegistryServiceDeleteResponse {
        deleted?: boolean;
        delete_time?: string;
        mod_revision?: string;
      }
      export interface MeasureRegistryServiceGetRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface MeasureRegistryServiceGetResponse {
        measure?: banyandb.database.v1.Measure | null;
      }
      export interface MeasureRegistryServiceListRequest {
        group?: string;
      }
      export interface MeasureRegistryServiceListResponse {
        measure?: banyandb.database.v1.Measure[];
      }
      export interface MeasureRegistryServiceExistRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface MeasureRegistryServiceExistResponse {
        has_group?: boolean;
        has_measure?: boolean;
      }
      export interface GroupRegistryServiceCreateRequest {
        group?: banyandb.common.v1.Group | null;
      }
      export interface GroupRegistryServiceCreateResponse {
        mod_revision?: string;
      }
      export interface GroupRegistryServiceUpdateRequest {
        group?: banyandb.common.v1.Group | null;
      }
      export interface GroupRegistryServiceUpdateResponse {
        mod_revision?: string;
      }
      export interface GroupRegistryServiceDeleteRequest {
        group?: string;
        dry_run?: boolean;
        force?: boolean;
        data_only?: boolean;
      }
      export interface GroupRegistryServiceDeleteResponse {
        schema_info?: banyandb.database.v1.SchemaInfo | null;
        delete_time?: string;
        mod_revision?: string;
      }
      export interface GroupDeletionTask {
        current_phase?: banyandb.database.v1.GroupDeletionTask.Phase;
        total_counts?: Partial<Record<string, number>>;
        deleted_counts?: Partial<Record<string, number>>;
        total_data_size_bytes?: string;
        deleted_data_size_bytes?: string;
        message?: string;
        created_at?: google.protobuf.Timestamp | null;
        updated_at?: google.protobuf.Timestamp | null;
      }
      export namespace GroupDeletionTask {
        export type Phase = 'PHASE_UNSPECIFIED' | 'PHASE_PENDING' | 'PHASE_IN_PROGRESS' | 'PHASE_COMPLETED' | 'PHASE_FAILED';
      }
      export interface GroupRegistryServiceQueryRequest {
        group?: string;
      }
      export interface GroupRegistryServiceQueryResponse {
        task?: banyandb.database.v1.GroupDeletionTask | null;
      }
      export interface GroupRegistryServiceGetRequest {
        group?: string;
      }
      export interface GroupRegistryServiceGetResponse {
        group?: banyandb.common.v1.Group | null;
      }
      export interface GroupRegistryServiceListRequest {
      }
      export interface GroupRegistryServiceListResponse {
        group?: banyandb.common.v1.Group[];
      }
      export interface GroupRegistryServiceExistRequest {
        group?: string;
      }
      export interface GroupRegistryServiceExistResponse {
        has_group?: boolean;
      }
      export interface GroupRegistryServiceInspectRequest {
        group?: string;
      }
      export interface GroupRegistryServiceInspectResponse {
        group?: banyandb.common.v1.Group | null;
        schema_info?: banyandb.database.v1.SchemaInfo | null;
        data_info?: banyandb.database.v1.DataInfo[];
        liaison_info?: banyandb.database.v1.LiaisonInfo[];
      }
      export interface SchemaInfo {
        streams?: string[];
        measures?: string[];
        traces?: string[];
        properties?: string[];
        index_rules?: string[];
        index_rule_bindings?: string[];
        topn_aggregations?: string[];
      }
      export interface DataInfo {
        node?: banyandb.database.v1.Node | null;
        segment_info?: banyandb.database.v1.SegmentInfo[];
        data_size_bytes?: string;
      }
      export interface SegmentInfo {
        segment_id?: string;
        time_range_start?: string;
        time_range_end?: string;
        shard_info?: banyandb.database.v1.ShardInfo[];
        series_index_info?: banyandb.database.v1.SeriesIndexInfo | null;
      }
      export interface ShardInfo {
        shard_id?: number;
        data_count?: string;
        data_size_bytes?: string;
        part_count?: string;
        inverted_index_info?: banyandb.database.v1.InvertedIndexInfo | null;
        sidx_info?: banyandb.database.v1.SIDXInfo | null;
        file_part_count?: string;
      }
      export interface SeriesIndexInfo {
        data_count?: string;
        data_size_bytes?: string;
      }
      export interface InvertedIndexInfo {
        data_count?: string;
        data_size_bytes?: string;
      }
      export interface SIDXInfo {
        data_count?: string;
        data_size_bytes?: string;
        part_count?: string;
      }
      export interface LiaisonInfo {
        pending_write_data_count?: string;
        pending_sync_part_count?: string;
        pending_sync_data_size_bytes?: string;
        pending_handoff_part_count?: string;
        pending_handoff_data_size_bytes?: string;
      }
      export interface TopNAggregationRegistryServiceCreateRequest {
        top_n_aggregation?: banyandb.database.v1.TopNAggregation | null;
      }
      export interface TopNAggregationRegistryServiceCreateResponse {
        mod_revision?: string;
      }
      export interface TopNAggregationRegistryServiceUpdateRequest {
        top_n_aggregation?: banyandb.database.v1.TopNAggregation | null;
      }
      export interface TopNAggregationRegistryServiceUpdateResponse {
        mod_revision?: string;
      }
      export interface TopNAggregationRegistryServiceDeleteRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface TopNAggregationRegistryServiceDeleteResponse {
        deleted?: boolean;
        delete_time?: string;
        mod_revision?: string;
      }
      export interface TopNAggregationRegistryServiceGetRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface TopNAggregationRegistryServiceGetResponse {
        top_n_aggregation?: banyandb.database.v1.TopNAggregation | null;
      }
      export interface TopNAggregationRegistryServiceListRequest {
        group?: string;
      }
      export interface TopNAggregationRegistryServiceListResponse {
        top_n_aggregation?: banyandb.database.v1.TopNAggregation[];
      }
      export interface TopNAggregationRegistryServiceExistRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface TopNAggregationRegistryServiceExistResponse {
        has_group?: boolean;
        has_top_n_aggregation?: boolean;
      }
      export interface SnapshotRequest {
        groups?: banyandb.database.v1.SnapshotRequest.Group[];
      }
      export namespace SnapshotRequest {
        export interface Group {
          catalog?: banyandb.common.v1.Catalog;
          group?: string;
        }
      }
      export interface Snapshot {
        catalog?: banyandb.common.v1.Catalog;
        name?: string;
        error?: string;
      }
      export interface SnapshotResponse {
        snapshots?: banyandb.database.v1.Snapshot[];
      }
      export interface PropertyRegistryServiceCreateRequest {
        property?: banyandb.database.v1.Property | null;
      }
      export interface PropertyRegistryServiceCreateResponse {
        mod_revision?: string;
      }
      export interface PropertyRegistryServiceUpdateRequest {
        property?: banyandb.database.v1.Property | null;
      }
      export interface PropertyRegistryServiceUpdateResponse {
        mod_revision?: string;
      }
      export interface PropertyRegistryServiceDeleteRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface PropertyRegistryServiceDeleteResponse {
        deleted?: boolean;
        delete_time?: string;
        mod_revision?: string;
      }
      export interface PropertyRegistryServiceGetRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface PropertyRegistryServiceGetResponse {
        property?: banyandb.database.v1.Property | null;
      }
      export interface PropertyRegistryServiceListRequest {
        group?: string;
      }
      export interface PropertyRegistryServiceListResponse {
        properties?: banyandb.database.v1.Property[];
      }
      export interface PropertyRegistryServiceExistRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface PropertyRegistryServiceExistResponse {
        has_group?: boolean;
        has_property?: boolean;
      }
      export interface TraceRegistryServiceCreateRequest {
        trace?: banyandb.database.v1.Trace | null;
      }
      export interface TraceRegistryServiceCreateResponse {
        mod_revision?: string;
      }
      export interface TraceRegistryServiceUpdateRequest {
        trace?: banyandb.database.v1.Trace | null;
      }
      export interface TraceRegistryServiceUpdateResponse {
        mod_revision?: string;
      }
      export interface TraceRegistryServiceDeleteRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface TraceRegistryServiceDeleteResponse {
        deleted?: boolean;
        delete_time?: string;
        mod_revision?: string;
      }
      export interface TraceRegistryServiceGetRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface TraceRegistryServiceGetResponse {
        trace?: banyandb.database.v1.Trace | null;
      }
      export interface TraceRegistryServiceExistRequest {
        metadata?: banyandb.common.v1.Metadata | null;
      }
      export interface TraceRegistryServiceExistResponse {
        has_group?: boolean;
        has_trace?: boolean;
      }
      export interface TraceRegistryServiceListRequest {
        group?: string;
      }
      export interface TraceRegistryServiceListResponse {
        trace?: banyandb.database.v1.Trace[];
      }
      export interface GetCurrentNodeRequest {
      }
      export interface GetCurrentNodeResponse {
        node?: banyandb.database.v1.Node | null;
      }
      export interface GetClusterStateRequest {
      }
      export interface RouteTable {
        registered?: banyandb.database.v1.Node[];
        active?: string[];
        evictable?: string[];
      }
      export interface GetClusterStateResponse {
        route_tables?: Partial<Record<string, banyandb.database.v1.RouteTable>>;
      }
    }
  }
  export namespace stream {
    export namespace v1 {
      export interface Element {
        element_id?: string;
        timestamp?: google.protobuf.Timestamp | null;
        tag_families?: banyandb.model.v1.TagFamily[];
      }
      export interface QueryResponse {
        elements?: banyandb.stream.v1.Element[];
        trace?: banyandb.common.v1.Trace | null;
        group_statuses?: Partial<Record<string, banyandb.model.v1.Status>>;
      }
      export interface QueryRequest {
        groups?: string[];
        name?: string;
        time_range?: banyandb.model.v1.TimeRange | null;
        offset?: number;
        limit?: number;
        order_by?: banyandb.model.v1.QueryOrder | null;
        criteria?: banyandb.model.v1.Criteria | null;
        projection?: banyandb.model.v1.TagProjection | null;
        trace?: boolean;
        stages?: string[];
        group_mod_revisions?: Partial<Record<string, string>>;
      }
      export interface TagFamilySpec {
        name?: string;
        tag_names?: string[];
      }
      export interface ElementValue {
        element_id?: string;
        timestamp?: google.protobuf.Timestamp | null;
        tag_families?: banyandb.model.v1.TagFamilyForWrite[];
      }
      export interface WriteRequest {
        metadata?: banyandb.common.v1.Metadata | null;
        element?: banyandb.stream.v1.ElementValue | null;
        message_id?: string;
        tag_family_spec?: banyandb.stream.v1.TagFamilySpec[];
      }
      export interface WriteResponse {
        message_id?: string;
        status?: string;
        metadata?: banyandb.common.v1.Metadata | null;
      }
    }
  }
  export namespace measure {
    export namespace v1 {
      export interface DataPoint {
        timestamp?: google.protobuf.Timestamp | null;
        tag_families?: banyandb.model.v1.TagFamily[];
        fields?: banyandb.measure.v1.DataPoint.Field[];
        sid?: string;
        version?: string;
      }
      export namespace DataPoint {
        export interface Field {
          name?: string;
          value?: banyandb.model.v1.FieldValue | null;
        }
      }
      export interface QueryResponse {
        data_points?: banyandb.measure.v1.DataPoint[];
        trace?: banyandb.common.v1.Trace | null;
        group_statuses?: Partial<Record<string, banyandb.model.v1.Status>>;
      }
      export interface InternalDataPoint {
        data_point?: banyandb.measure.v1.DataPoint | null;
        shard_id?: number;
      }
      export interface InternalQueryRequest {
        request?: banyandb.measure.v1.QueryRequest | null;
        agg_return_partial?: boolean;
      }
      export interface InternalQueryResponse {
        data_points?: banyandb.measure.v1.InternalDataPoint[];
        trace?: banyandb.common.v1.Trace | null;
        raw_frame_body?: Buffer;
      }
      export interface QueryRequest {
        groups?: string[];
        name?: string;
        time_range?: banyandb.model.v1.TimeRange | null;
        criteria?: banyandb.model.v1.Criteria | null;
        tag_projection?: banyandb.model.v1.TagProjection | null;
        field_projection?: banyandb.measure.v1.QueryRequest.FieldProjection | null;
        group_by?: banyandb.measure.v1.QueryRequest.GroupBy | null;
        agg?: banyandb.measure.v1.QueryRequest.Aggregation | null;
        top?: banyandb.measure.v1.QueryRequest.Top | null;
        offset?: number;
        limit?: number;
        order_by?: banyandb.model.v1.QueryOrder | null;
        trace?: boolean;
        stages?: string[];
        rewrite_agg_top_n_result?: boolean;
        group_mod_revisions?: Partial<Record<string, string>>;
      }
      export namespace QueryRequest {
        export interface FieldProjection {
          names?: string[];
        }
        export interface GroupBy {
          tag_projection?: banyandb.model.v1.TagProjection | null;
          field_name?: string;
        }
        export interface Aggregation {
          function?: banyandb.model.v1.AggregationFunction;
          field_name?: string;
        }
        export interface Top {
          number?: number;
          field_name?: string;
          field_value_sort?: banyandb.model.v1.Sort;
        }
      }
      export interface TopNList {
        timestamp?: google.protobuf.Timestamp | null;
        items?: banyandb.measure.v1.TopNList.Item[];
      }
      export namespace TopNList {
        export interface Item {
          entity?: banyandb.model.v1.Tag[];
          value?: banyandb.model.v1.FieldValue | null;
          version?: string;
          timestamp?: google.protobuf.Timestamp | null;
        }
      }
      export interface TopNResponse {
        lists?: banyandb.measure.v1.TopNList[];
        trace?: banyandb.common.v1.Trace | null;
      }
      export interface TopNRequest {
        groups?: string[];
        name?: string;
        time_range?: banyandb.model.v1.TimeRange | null;
        top_n?: number;
        agg?: banyandb.model.v1.AggregationFunction;
        conditions?: banyandb.model.v1.Condition[];
        field_value_sort?: banyandb.model.v1.Sort;
        trace?: boolean;
        stages?: string[];
      }
      export interface TagFamilySpec {
        name?: string;
        tag_names?: string[];
      }
      export interface DataPointSpec {
        tag_family_spec?: banyandb.measure.v1.TagFamilySpec[];
        field_names?: string[];
      }
      export interface DataPointValue {
        timestamp?: google.protobuf.Timestamp | null;
        tag_families?: banyandb.model.v1.TagFamilyForWrite[];
        fields?: banyandb.model.v1.FieldValue[];
        version?: string;
      }
      export interface WriteRequest {
        metadata?: banyandb.common.v1.Metadata | null;
        data_point?: banyandb.measure.v1.DataPointValue | null;
        message_id?: string;
        data_point_spec?: banyandb.measure.v1.DataPointSpec | null;
      }
      export interface WriteResponse {
        message_id?: string;
        status?: string;
        metadata?: banyandb.common.v1.Metadata | null;
      }
    }
  }
  export namespace schema {
    export namespace v1 {
      export interface SchemaKey {
        kind?: string;
        group?: string;
        name?: string;
      }
      export interface NodeLaggard {
        node?: string;
        current_mod_revision?: string;
        missing_keys?: banyandb.schema.v1.SchemaKey[];
        still_present_keys?: banyandb.schema.v1.SchemaKey[];
      }
      export interface AwaitRevisionAppliedRequest {
        min_revision?: string;
        timeout?: google.protobuf.Duration | null;
      }
      export interface AwaitRevisionAppliedResponse {
        applied?: boolean;
        laggards?: banyandb.schema.v1.NodeLaggard[];
      }
      export interface AwaitSchemaAppliedRequest {
        keys?: banyandb.schema.v1.SchemaKey[];
        min_revisions?: string[];
        timeout?: google.protobuf.Duration | null;
      }
      export interface AwaitSchemaAppliedResponse {
        applied?: boolean;
        laggards?: banyandb.schema.v1.NodeLaggard[];
      }
      export interface AwaitSchemaDeletedRequest {
        keys?: banyandb.schema.v1.SchemaKey[];
        timeout?: google.protobuf.Duration | null;
      }
      export interface AwaitSchemaDeletedResponse {
        applied?: boolean;
        laggards?: banyandb.schema.v1.NodeLaggard[];
      }
    }
  }
}
export namespace google {
  export namespace protobuf {
      export interface Duration {
        seconds?: string;
        nanos?: number;
      }
      export interface ListValue {
        values?: google.protobuf.Value[];
      }
      export type NullValue = 'NULL_VALUE';
      export interface Struct {
        fields?: Record<string, google.protobuf.Value>;
      }
      export interface Timestamp {
        seconds?: string;
        nanos?: number;
      }
      export interface Value {
        nullValue?: google.protobuf.NullValue;
        numberValue?: number;
        stringValue?: string;
        boolValue?: boolean;
        structValue?: google.protobuf.Struct;
        listValue?: google.protobuf.ListValue;
        kind?: 'nullValue' | 'numberValue' | 'stringValue' | 'boolValue' | 'structValue' | 'listValue';
      }
  }
}
